### ISSUE TITLE
Не понимает длинные пути Linux

### ISSUE THREAD

**Issue by konarev** [rupor-github/fb2mobi#1]
Неправильная работа при указании путей в стиле Linux (деление директорий правым косой слэш '/', экранирование пробелов левым слэшем '\'). Пути пытается понимать как параметры. 
Например:
fb2mobi /tmp/К/Клавелл\ Джеймс/Сегун.fb2  /run/media/username/Kindle/Сегун.mobi
fb2mobi.py: error: unrecognized arguments: /run/media/username/Kindle/Сегун.mobi

С короткими именами путей (/tmp/file.fb2), работает нормально

**Comment by rupor-github** [comment]
А вы не пробовали брать в кавычки? Как-то скажем так:

fb2mobi "/tmp/К/Клавелл\ Джеймс/Сегун.fb2" "/run/media/username/Kindle/Сегун.mobi" ?

Я конечно посмотрю что-там не так на выходных.

**Comment by konarev** [comment]
Да, пробовал. Не помогло..

**Comment by rupor-github** [comment]
Убедитесь пожалуйста, что fb2mobi.py использует python3 (измените первую строчку в файле или возьмите свежий master). Все работает:

```
$ ./fb2mobi.py $HOME/fb2mobi/Toward\ the\ End\ of\ Time.fb2
INFO: Converting "Toward the End of Time.fb2"...
INFO: Using profile "spaces".
INFO: Converting to html...
INFO: Applying XSLT transformations "/home/user/fb2mobi/spaces.xsl"
INFO: Converting to html took 1.32 sec.
INFO: Running kindlegen...
INFO: Extracting azw3 from mobi...
INFO: Book convertion completed in 1.35 sec.
```
Получается что-то вроде:
```
-rw-r--r--  1 user user 541K Jul  1 19:58 Toward the End of Time.azw3
-rw-r--r--  1 user user 708K Jul  1 19:33 Toward the End of Time.fb2
```
