### ISSUE TITLE
macos: pointer being freed was not allocated

### ISSUE THREAD

**Issue by muRn** [rupor-github/fb2mobi#12]
Не уверен что проблема в самом fb2mobi, возможно у меня просто какая-то библиотека старая или кривая. Вот что примерно происходит:

$ python3 fb2mobi.py ../books/fb2/112552.fb2 test.mobi
INFO: Converting "112552.fb2"...
INFO: Using profile "default".
INFO: Converting fb2 to html...
INFO: Applying XSLT transformations "/Users/muRn/PycharmProjects/bot/fb2mobi/spaces.xsl"
Python(3684,0x7fff75710000) malloc: *** error for object 0x10383c870: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

--console-level DEBUG --log somefile.log не дают никакой дополнительной информации

Python 3.6.0

Есть идеи из-за чего это может происходить?

**Comment by rupor-github** [comment]
Да, есть - на Windows с Python 3.6 не работает memory allocator в PyHyphen. Проверьте с выключенным hyphenator, если будет работать, то PyHyphen надо пересобрать из моего форк'а.

**Comment by muRn** [comment]
Да, флаг --no-hyphenate помог, спасибо большое! Только сейчас увидел, что в README.md про эту ошибку сказано, но там написано что это происходит на Windows. Как оказалось, не только :(

**Comment by rupor-github** [comment]
Я просто не могу проверить он MAC, а на Linux я поленился. Readme я поправлю
