### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by ololoe** [rupor-github/fb2mobi#2]
У меня тоже было желание допилить сабж, т.к. заполняет полезную нишу (калибр со встроенным конвертером уж очень тормознут, да и не переносит в один клик), но уж очень говнокодист.

Какие у тебя планы по развитию сабжа? У меня такие:

* Разбиение на модули, которые можно было бы использовать вне программы. Особенно интересует создание epub из html файлов (программа же и создает распакованный epub а потом скармливает его kindlegen-у?).
* Та версия работала только с определенной версией wx, да и вообще можно перейти, скажем, на qt. Гуй весьма примитивный.

**Comment by rupor-github** [comment]
Привет

У меня никаких определенных планов нет, кроме пожалуй желания удерживать программу в исключительно стабильном и функциональном состоянии. Дело в том, что у меня сравнительно немного времени. Когда есть свободное я иногда обдумываю как расширить epub->mobi/azw функциональность, например можно было бы пытаться обрабатывать css в epub'e, сливая внешнуй css с epub и добиваясь некого общего вида книги. Неплохо было бы уйти с Python - ибо медленно, но это совсем не обязательно.

GUI в "моей" версии сейчас нет - и не будет, так как КМК это должем быть отдельный независимый проект. Здесь, конечно, полный простор для полета.

Модули, особенно модуль для создания epub из html - боюсь это я не по адресу. Основная функциональность сегодня это генерация xhtml из FB2 - это существенно менее общая задача.

**Comment by ololoe** [comment]
>Неплохо было бы уйти с Python - ибо медленно
Как по мне - не критично, калибр гораздо медленнее. Даже так как есть, по ощущениям - большая часть времени уходит именно на kindlegen.

> Модули, особенно модуль для создания epub из html - боюсь это я не по адресу. Основная функциональность сегодня это генерация xhtml из FB2 - это существенно менее общая задача.
Ну а потом что с ними происходит? Добавляются какие-то метафайлы, внешне похожие на потроха epub и это скармливается киндлгену? Мне нужно готовые (x)html файлы оформить как epub, это разве не то же самое?

>GUI в "моей" версии сейчас нет - и не будет, так как КМК это должем быть отдельный независимый проект. 
Вообще нет что ли? Такс, а какие еще изменения по сравнению с оригиналом?

**Comment by rupor-github** [comment]
У Python есть и еще недостаток - производить binaries для расспространения чрезвычайно муторно и убого.

"Какие-то" метафайлы - это информация, берущаяся из fb2 в процессе производства xhtml файлов. Как мне кажется код никогда не задумывался как сколько-нибудь уневерсальный модуль. Мне думается, что использовать его как источник информации при написании чего-то похожего можно, а вот "оформлять" как универсальный - ничего хорошего не получится, увы. Проще уж использовать https://pypi.python.org/pypi/epubmaker, он для этого и был создан.

Основные изменения описаны на первой странице поекта, прочитать небольшокй труд. Ну и git вроде работает - если я правильно помню, я сначала положил оригинальный код, а потом менял - так что вся история проекта к вашим услугам.

**Comment by ololoe** [comment]
UI != GUI

Гуй совсем убит что ли?

**Comment by ololoe** [comment]
Без гуя не интересно. Никто больше не пилит сабж, не в курсе?

**Comment by ololoe** [comment]
Такс, мне кажется или тут был мой комент?

**Comment by rupor-github** [comment]
Давайте оставим issues для того, для чего они были предназначены - проблем. Комментарии типа "UI != GUI" и подобные вещи можно обсудить в других местах. Например здесь: http://www.the-ebook.org/forum/viewforum.php?f=4

**Comment by ololoe** [comment]
К чему мне вообще лезть в ту помойку? Что я там не видел? И зачем **там** обсуждать, что из оригинальной программы **ты** оставил, а что - нет? И вообще, трут только пидорасы.

**Comment by ololoe** [comment]
Во, я ж помню, что я здесь уже был. Хорошо что таки сделали гуй. Плохо он мне не нужен :)

**Comment by ololoe** [comment]
Что именно скармливается киндлегену? Можно ли вместо этого скармливать epub? Это добавит возможность конвертировать в епуб и решит проблему когда не работает kindlegen - можно будет использовать другой конвертер.

**Comment by rupor-github** [comment]
Вы бы почитали WiKi - epub давно поддержан, как на входе, так и на выходе.
