### ISSUE TITLE
Footnote links in superscript without CSS rules

### ISSUE THREAD

**Issue by mshkrebtan** [rupor-github/fb2mobi#20]
I have noticed that every hyper-link, including footnote links, belongs to class `anchor` and each `anchor` is aligned via CSS like this:

```
.anchor {
    vertical-align: super;
    font-size: 70%;
}
```

However, not every hyper-link is a footnote link. Many non-fiction books contain usual hyper-links as well as footnote links.  Usual “inline” hyper-links therefore should not be superscripted.

Amazon recommends (even requires) footnote links to be superscripted with the `<sup>` HTML tag, see [here](https://kdp.amazon.com/help?topicId=A1IZ6N1F51ZYJ2).

Is it possible to add an option for that or just make it the default behaviour?

**Comment by rupor-github** [comment]
Not sure I understand what you are saying fully. The part with superscript if more or less clear - I'll take a look to see if it makes sense and how to add this. The part about "not every link is a footnote link" is less so - if I remember correctly only those that point to content in "notes" section are converted to footnotes.

**Comment by mshkrebtan** [comment]
@rupor-github 

What I mean is that sometimes you can meet usual links within text, like [this](https://github.com/rupor-github/fb2mobi/issues/20#), and in a converted book they will be superscripted (via a CSS rule for `.anchor`, for example) and it looks ugly.

I think the only links that should be superscripted are footnote links. This could be achieved via removing the CSS rule for `.anchor` and superscripting each `[number]` footnote link with the `<sup>` tag.

**Comment by rupor-github** [comment]
"I think the only links that should be superscripted are footnote links. This could be achieved via removing the CSS rule for .anchor and superscripting each [number] footnote link with the <sup> tag."

I do not think this suggestion would work, at least not reliably. For example there are books with "notes" and "comments" sections, in which notes are not formatted as [number] and comments are... Good example of such formatting is http://flibusta.is/b/240113.  It already has <sup> formatting on comments, but not on notes.

**Comment by rupor-github** [comment]
@mshkrebtan 

Hyperlinks, pointing into sections recognized as "notebodies" now have different css class (.anchor) from other links (.linkanchor). This allows for flexible formatting - basically you could do whatever you want with your style without braking backward compatibility or using additional command options.

For kindlegen there is no difference in using tag `<sup` and css class with `vertical-align: super;` - both are properly recognized as being "the same".

**Comment by mshkrebtan** [comment]
@rupor-github 

Thank you!
