### ISSUE TITLE
А можно файл requirements.txt в сорцы?

### ISSUE THREAD

**Issue by suguby** [rupor-github/fb2mobi#3]
У меня вот с этим 
(fb2mobi_env)wad@wad-think2:~/PycharmProjects/fb2mobi (master)$ pip freeze
Pillow==3.3.0
PyHyphen==2.0.5
cssutils==1.0.1
lxml==3.6.0
собралось и сконвертировалось под 
(fb2mobi_env)wad@wad-think2:~/PycharmProjects/fb2mobi (master)$ uname -a
Linux wad-think2 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rupor-github** [comment]
Вы не могли бы пояснить что именно вы просите? А то я нифига не понял...

**Comment by suguby** [comment]
в корне проекта создать файл requirements.txt и туда записать список пакетов, которые нужны для запуска:
Pillow==3.3.0
PyHyphen==2.0.5
cssutils==1.0.1
lxml==3.6.0

мне пришлось по коду лазить и устанавливать поодиночке... http://intopython.ru/blog/konvertatsiia-fb2-knig-v-mobi-format-dlia-kindle

**Comment by suguby** [comment]
еще могу помочь с выкладыванием на PyPi - тогда вообще просто ставить pip install fb2mobi :)

**Comment by rupor-github** [comment]
Я дописал список модулей в readme.  Никогда не думал, что под Linux нужно собирать freeze. На всех Linux где я работаю есть Python 3...

Насчет PyPi - я поддерживать это не буду, мне вполне хватает того, что я уже делаю на github. Если вы будете вести такую distribution - пожалуйста, выкладывайте. Если же у вас нет планов за этим постоянно следить - тогда лучше не надо. Уже есть мертвые сборки в Arch...
