### ISSUE TITLE
Cannot process the original python manual.

### ISSUE THREAD

**Issue by JulyMorning** [rupor-github/fb2mobi#32]
Took it [there](https://docs.python.org/3/download.html), [log](https://github.com/rupor-github/fb2mobi/files/1548762/err.txt).

**Comment by rupor-github** [comment]
I am not sure what do I have to do about it -  if anything. After all kindlegen is closed source maintained by Amazon, may be it make sense to complain to them instead?

"Error(parsing):E3013: More number of characters are hidden using display:none than allowed limit. Limit: 10000  in file: 10000 line: 10000"
