### ISSUE TITLE
Поддержка XP

### ISSUE THREAD

**Issue by ololoe** [rupor-github/fb2mobi#35]
Последняя версия питона которая работает на XP - 3.4. Совместима ли программа  с ним?
Сам проверить пока не могу, на него нет какого-то скомпилированного модуля.

**Comment by rupor-github** [comment]
Программа проверяется ТОЛЬКО на заявленной версии питона - сейчас 3.6.5.  Можно найти старую (ту, которая строилась с 3.4)  версию в релизах и использовать на XP именно ее. Никакой работы в этом направлении разработчиками не планируется.

**Comment by ololoe** [comment]
Есть какие-то ограничения, почему она не пойдет на 3.4 или просто влом?

**Comment by rupor-github** [comment]
Не понятно зачем тратить время

**Comment by ololoe** [comment]
А какие затраты времени кроме указания другой версии в пути? Разница там должна быть минимальной, это же не 2 и 3.

**Comment by rupor-github** [comment]
Давайте вы создадите форк, добавите его в PyPl и будете maintain? А я с удовольствием переключу на него программу?

**Comment by rupor-github** [comment]
Я извиняюсь - не понял вопроса, так что про форк снимается. Обычно построенная программа тестируется - хотябы минимимально. Это требует времени.

**Comment by ololoe** [comment]
Я очень сомневаюсь, что на 3.4 и последней версии будут разные баги. Но переубедить вас похоже не получится.

**Comment by rupor-github** [comment]
Поддерживать XP и Python 3.4? Не получится.

**Comment by ololoe** [comment]
Просто 3.4 хотя бы.
