### ISSUE TITLE
Поддержка юникода

### ISSUE THREAD

**Issue by ololoe** [rupor-github/fb2mobi#36]
> Original program (being Python 2) did not work well under Windows when non-russian system codepage was selected for non-Unicode programs. In order to improve the situation I had to port it to Python 3.

Для этого было необязятельно портировать под тройку, но если спортировали - только плюс. Остались еще какие-то проблемы с юникодом?

https://github.com/rupor-github/fb2mobi/wiki/Настройка-программы-(версия-с-графическим-интерфейсом)
> Замечание для пользователей Microsof Windows. Если путь к папке шрифтов содержит символы, отличные от латиницы (кириллицу и т.п.), функция выбора шрифтов будет недоступна из-за некорректной работы с unicode некоторыми библиотеками, используемыми в конвертере. Если вы устанавливали программу с помощью инсталлятора, перенесите все файлы и папки из папки c:\Users<Имя_пользователя>\fb2mobi в папку программы c:\Program Files\fb2mobi. Папку c:\Users<Имя_пользователя>\fb2mobi удалите. Если вы устанавливали программу из архива, проверьте, что в путь к папке, куда вы установили программу, не содержит символов, отличных от латиницы.

Это еще актуально? В чем конкретно проблема?

**Comment by rupor-github** [comment]
Проблема в pyhyphen - https://bitbucket.org/fhaxbox66/pyhyphen/pull-requests/4/making-sure-that-pyhyphen-properly/diff

**Comment by ololoe** [comment]
Там пулл реквест мержить не хотят? Что такое pyhyphen? Сишный модуль переносов? Чем не угодил тот что был в старой версии?

**Comment by rupor-github** [comment]
В старой версии использовался trie based custom dictionary работавший (если я правильно помню) на 3 языка. Не было возможности его расширения. Новая работает на стандартных словарях, поддержанных в LibreOffice, Mozila и т.д. и не имеет ограничений такого рода. Насчет хотят ли они смерживать pull request - вам лучше поинтересоваться у авторов pyhyphen.

**Comment by ololoe** [comment]
> Насчет хотят ли они смерживать pull request - вам лучше поинтересоваться у авторов pyhyphen.
Я спросил в чем там проблема - что есть пулл реквест но они не хотят его мержить? Нету форка или желания смержить самому? Проблемы с юникодными путями в 2018 как бы не комильфо.

**Comment by rupor-github** [comment]
Что касается "Для этого было необязятельно портировать под тройку" - Python 2 под виндовс много вешей делает неправильно - неправильно работает с Unicode command line, неправильно выводит Unicode на console и т.д. Заниматься борьбой с этим можно, но непонятно зачем - как и непонятно зачем поддерживать Windows XP.

**Comment by rupor-github** [comment]
Я довольно долго поддерживал форк pyhyphen, он у меня до сих пор по-моему в repositories есть. За все время проблема с путем была у 2-х пользователей, а объяснять, что делать с форком пришлось раз 200. Время жалко.

**Comment by ololoe** [comment]
> объяснять, что делать с форком 
Но зачем? Делаем форк, добавляем в pypi, делаем колёса, меняем в зависимостях проекта. Всё.

Порт на тройку конечно более правильный вариант, но и более ресурсоёмкий. Но если уже сделали то хорошо.

**Comment by rupor-github** [comment]
Если вы готовы этим заниматься - я с удовольствием перейду на ваш форк. При условии что вы будете следить и update его, когда меняется питон, хотя бы для трех OS

**Comment by rupor-github** [comment]
Мне кажется вся история PR на bitbucket доступна. Я не знаю в чем там проблема - с кодом мне кажется они согласились, но ждут какого-то события чтобы автоматически проверять модуль на совместимость с разнообразными версиями питона перед публикацией в pypi. Так что я тоже не в курсе.

**Comment by ololoe** [comment]
Я про этот баг первый раз слышу, думал, вы больше знаете. Если изменений с момента пуша не было, то следить не зачем.
Впрочем, мне кажется, разговоры с вами бессмысленны. Я пользуюсь старой версией с пофикшенными багами, значит, буду ей и дальше пользоваться.

**Comment by rupor-github** [comment]
Разговоры в подобном тоне бессмысленны по определению - это было понятно еще в первый раз. В форуме ясно написано - это не моя основная работа, я делаю программу для себя и делюсь результатами. Стараюсь устранять проблемы - если они имеют для меня хоть какой-то смысл. То, о чем говорите вы - не имеет, по крайней мере я понять вас не смог. Если вы хотите участвовать в  разработке - берите и делайте, как делают другие участники. Лишнего времени ни у кого нет. Считаете что Python 3.4 и 3.6 одинаковы - пользуйтесь кодом под 3.4, в чем проблема? Хотите предложить поддержанный форк pyhyphen - все будут только рады вашему участию.

**Comment by ololoe** [comment]
С таким потребительским отношением точно ничего не выйдет. Если вас даже баги с юникодом устраивают... Не вижу причины тратить на какую-то помощь в разработке ни секунды времени. Из принципа.

**Comment by rupor-github** [comment]
Я (видимо в отличие от вас) потратил кучу времени на починку проблем с Unicode - потрудившись создать сначала форки а потом и proper PR авторам. Все это описано в форуме.

**Comment by rupor-github** [comment]
Ну да, поискать в теме видимо трудно. Почти невозможно. Понимаю.

**Comment by KainXVIII** [comment]
Засрали мне весь ящик с упоминаниями =(
