### ISSUE TITLE
Неточности и огрехи

### ISSUE THREAD

**Issue by n-osennij** [rupor-github/fb2mobi#39]
[В документации](https://github.com/rupor-github/fb2mobi/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BE%D0%B9-(%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-%D1%81-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%BC-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%BC)#%D0%9E%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-gmail) указано, что нужно использовать в программе с графическим интерфейссом (страница ведь "Работа с программой (версия с графическим интерфейсом)") утилиту synccovers для синхронизации обложек. Вместе с тем [вот тут](https://github.com/rupor-github/fb2mobi/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-fb2mobi.config#kindleremovepersonallabel) указано

> Для версии с графическим интерфейсом это не требуется - программа автоматически создает миниатюры обложек при отправке книг на устройство Kindle.

Как бы там ни было, а обложки упорно не хотят приходить на мой PW3  с последними обновлениями (при отправке через отправке сконвертированных mobi книг почтой как вручную, так и почтой через программу; версия программы самая последняя - 3.6.65)

Также [указано](https://github.com/rupor-github/fb2mobi/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-fb2mobi.config#kindleremovepersonallabel) , что `kindleRemovePersonalLabel = true` позволит добавлять книгу не в Docs, а в Books. На самом устройстве книги эти тоже не распознаются как книги, а распознаются как документы.

> Устройства Kindle различают книги, купленные в магазине Amazon и книги, созданные с помощью утилиты kindlegen. На старых версиях ПО прошивки Kindle книги, созданные с помощью kindlegen имели визуальную метку "Personal". Включение данной опции позволяет создать файл, который будет восприниматься устройством Kindle также, как и книга, купленная в Amazon, что позволяет удалить метку "Personal".

В остальном вроде бы всё отлично. Переносы в книге расставляются. Страницы синхронизируюся. Можно выделять отрывки и делиться ими в соцсетях. Всё очень удобно, быстро и практично. Коллекции уже можно быстро и удобно создать через браузер. Если бы ещё обложки нормально  работали и книги распознавались как книги - был бы просто космос!

**Comment by rupor-github** [comment]
Мне кажется, что в имеются ввиду разные аспекты работы программы. Отправка на устройство может означать 2 разных действия: 1. программа обнаруживает kindle, подлкюченный через USB и кладет туда книги. При этом synccovers не нужна - то, что она делает, будет сделано UI. Будут и обложки и распознаваться будут и книги и персональные документы. Форматы могут быть любые поддержанные. 2. отправка может означать послать через e-mail. В этом случае существуют ограничения, навязываемые Амазоном - например, отправить можно только mobi файл, будут проблемы с обложками (появляются только для старого формата mobi, но тогда нет переносов и тд и тп) и если я не ошибаюсь никаких "книг" Амазон не дает пересылать, Об этом написаны тонны инфо на разнообразных форумах.

**Comment by n-osennij** [comment]
@rupor-github Стало быть это безвыходная ситуация) Хочешь переносы и облако - не имей обложку. А хочешь обложку - откажись от облака и переносов.

А как быть с `kindleRemovePersonalLabel = true`? Изменения у них там какие-то, и теперь это не работает?

**Comment by rupor-github** [comment]
Почему? Работает - через USB можно положить как "персональный документ", так и книгу.

**Comment by n-osennij** [comment]
@rupor-github А, я подумал про облако...

**Comment by n-osennij** [comment]
@rupor-github А почему при конвертировании серий книг добавляются какие-то странные буквы перед номером серии? Откуда они вообще берутся?
- tsa 01
- б-гг 03
- х 01
Книги прикрепил ниже. Это просто три книги наобум.

[Bill, ghieroi Galaktiki, na pla - Garri Garrison.txt](https://github.com/rupor-github/fb2mobi/files/2194068/Bill.ghieroi.Galaktiki.na.pla.-.Garri.Garrison.txt)
[Dieti Linzy-1_ Sieryi Liensmien - Edvard Elmier Smit.txt](https://github.com/rupor-github/fb2mobi/files/2194069/Dieti.Linzy-1_.Sieryi.Liensmien.-.Edvard.Elmier.Smit.txt)
[Obriechiennoie korolievstvo - Briendon Sandierson.txt](https://github.com/rupor-github/fb2mobi/files/2194070/Obriechiennoie.korolievstvo.-.Briendon.Sandierson.txt)
