### ISSUE TITLE
fb2mobi on Windows 10 fails

### ISSUE THREAD

**Issue by ENikS** [rupor-github/fb2mobi#4]
Запуская exe получаю следующую ошибку:
```
C:\Program Files (x86)\MyHomeLib\converters\fb2mobi>fb2mobi.exe
Traceback (most recent call last):
  File "d:\python\python35_32\lib\site-packages\cx_freeze-5.0-py3.5-win32.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
  File "fb2mobi.py", line 588, in <module>
  File "fb2mobi.py", line 422, in process
  File "d:\python\python35_32\lib\logging\__init__.py", line 1008, in __init__
  File "d:\python\python35_32\lib\logging\__init__.py", line 1037, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\MyHomeLib\\converters\\fb2mobi\\debug.log'
```

Если запускать как Administrator, все работает как надо

**Comment by rupor-github** [comment]
Поправьте в fb2mobi.config путь к debug.log - направьте его куда-нибудь, где у программы есть permissions писать файлы.  Ну или запретите log file совсем, например:
  <logFile/>
  <logLevel>ERROR</logLevel>
Вы видимо первый, кто поставил программу в "Program Files" - но если серьезно прикладываемые конфиги это только примеры. Программу имеет смысл настраивать.

**Comment by ENikS** [comment]
Я не первый, кто поставил прогу в Program Files, я первый, кто указал на проблему в настройках. myHomeLib устанавливается в Program Files инстоллятором. 
Обычный юзер долго чешет репу, наконец находит вашу прогу и вываливает все файлы в предназначенную для  неё папку: C:\Program Files (x86)\MyHomeLib\converters\fb2mobi
На семерке все работает, а на десятке нет. Прога тихонько дохнёт без всяких ошибок. 
Я один из разработчиков myHomeLib с полным доступом к коду, поэтому я вижу, что происходит. К сожалению я не могу поправить проблему со стороны myHomeLib поэтому я предлагаю вам поправить конфигурацию, чтобы она работала без необходимости что то менять при инсталляции.

**Comment by rupor-github** [comment]
Женя, начнем с того, что я лог в следующем релизе выключу - это очень легоко. Теперь по делу: запрет лога по умолчанию плохо помогает - я неоднократно сталкивался с жалобами на смерть конвертера из под MyHomeLib не оставляющую никакой возможности понять что произошло. У программы (в том виде, в которм ее выпускаю я) нет installation - совсем. Конфигурация там исключительно для примера и ее все равно надо настраивать. Например в зависимости от устройства, на котором вы собираетесь читать. Если вы включаете ее в "свой" продукт - позаботьтесь о том, чтобы и конфигурация конвертеров была после исталляции соответствующая. Вообще то, как запускаются внешние конвертеры в MyHomeLib может/должно быть усовершенствовано. Что если у меня 2 Kindle с разными разрешениями экрана? Какую "правильную" конфигурацию я здесь должен выложить и кто будет объяснять почему на устройстве книга выглядит мягко говоря странно? И почему не проверяется return code?

**Comment by ENikS** [comment]
Я согласен, что интеграция могла бы быть лучше. Можно обсудить с Корейцем. Вы могли бы открыть тему в [dev](http://home-lib.net/) форуме и изложить свои мысли по вопросу?

Когда вы сможете поправить настройки?

**Comment by rupor-github** [comment]
Так вроде уже поправлено

**Comment by ENikS** [comment]
Я вечерком постараюсь оттестировать. Спасибо за быстрый fix.
Может вы могли бы написать коротенькую шпаргалку на форуме про настройки и т.д.? Даже я не особо понимаю как и что, а вроде не чайник...

**Comment by rupor-github** [comment]
Обсуждение обычно происходит [здесь](http://www.the-ebook.org/forum/viewtopic.php?t=30380) - я туда время от времени смотрю. Автор оригинального кода когда-то написал [документацию](https://www.dropbox.com/s/q2o2a0fb3urckgi/manual.pdf), большая часть которой вполне актуальна и сейчас. Отличия описаны в первом сообщении вышеупомянутой темы и с пользовательской точки зрения минимальны.

**Comment by ENikS** [comment]
С учетом того, что MyHomeLib  один из основных потребителей проги, шпаргалка на форуме с инфой и ссылками обсолютно не повредит. Но дело, конечно, хозяйское...

**Comment by rupor-github** [comment]
Наверно вы правы - я посмотрю, что я смогу сделать. Я даже не знал, что myhomelib forum еще жив.
