### ISSUE TITLE
Установка на Linux

### ISSUE THREAD

**Issue by n-osennij** [rupor-github/fb2mobi#41]
А есть ли более простая и доступная установка для Linux? С windows всё понятно - клац-клац, и готово.  А установка на linux - целая эпопея. Искать в каком-то файле список зависимостей. Искать, как их установить и т.д. Можно ли как-то собрать это в инструкции сразу (хотя бы для debian), потому что такие танцы - местный адок.

**Comment by rupor-github** [comment]
Для CLI  цли версии я выкладываю Ubuntu 16.04 совместимый билд - несколько человек его используют и вроде никто не жалуется. Для Для UI версии мне не так и не удалось сделать пакет, надежно работающий больше чем в одной дистрибуции. Если установить локально это адок - то я уж и не знаю как назвать пляски с бубном при попытке построить что-то осмысленное на linux используя Python freeze...

**Comment by n-osennij** [comment]
@rupor-github я вот про gui версию и говорю. Мне таки удалось как-то установить всё и запустить. И оно даже работало, но, например, список зависимостей - каждую пришлось скопировать и подставить в команду установки. Раз уже эти зависимости перечислены, так пусть уж они будут хотя бы через запятую, чтобы разом взять и установить.

**Comment by rupor-github** [comment]
Мне кажется вы горячитесь. Для этого и существует requirements.txt: 
`pip install -r requirements.txt`
устанавливает все необходимое разом - это не мы придумали.

**Comment by n-osennij** [comment]
@rupor-github Не знал о таком.. Было бы не плохо указать это. Мне как очень рядовому пользователю linux это бы очень жизнь облегчило. Ну и выше команду по установке pip

**Comment by n-osennij** [comment]
Я могу указать процедуру установки step by step под ubuntu 18.01.

**Comment by n-osennij** [comment]
Ну, смотрите сами) Я понимаю, что linux - слишком огромная часть пирога. Но по мне так описать установку для наиболее популярного диструбтива вполне оправдано. Вот купил kindle маме, например. У неё старенький ноут. Там mint xfce крутится. И явно бы подошла инструкция по установке от ubuntu. А у знакомой весь офис на ubuntu работает.

**Comment by n-osennij** [comment]
Спасибо за вашу работу!

**Comment by n-osennij** [comment]
К слову, если в gui нажать на значок "Добавить файлы из Google Drive", то откроется в браузере страница, где потребуется войти в гугл или выбрать свой аккаунт. Так вот, если эту вкладку закрыть (ну передумал я, например или что-то ещё), то gui зависает от слова совсем.

**Comment by rupor-github** [comment]
Это хорошо бы вынести в отдельное issue, интеграция с Google Drive экспериментальная, да и UI занимается @dnkorpushov, возможно он починит.
