### ISSUE TITLE
Hangs in UI when using Google Drive

### ISSUE THREAD

**Issue by rupor-github** [rupor-github/fb2mobi#42]
К слову, если в gui нажать на значок "Добавить файлы из Google Drive", то откроется в браузере страница, где потребуется войти в гугл или выбрать свой аккаунт. Так вот, если эту вкладку закрыть (ну передумал я, например или что-то ещё), то gui зависает от слова совсем.
Windows 10-64 latest (@n-osennij)

**Comment by dnkorpushov** [comment]
Из отпуска вернусь на следующей неделе, посмотрю
