### ISSUE TITLE
sendToKindle isn't working

### ISSUE THREAD

**Issue by xatage** [rupor-github/fb2mobi#44]
Books that are sent via sendToKindle are not added to the Kindle Library. That must be some special issue, because the sending itself works (I used sendToKindle to send to my own mail address without any problem) and there are no issues with my mail provider in connection with Amazon (sending the same book from web UI to Kindle Library works, too). But only the direct sending isn't working.

Maybe someone has an idea where to look at?

**Comment by rupor-github** [comment]
Возможно Amazon опять что-то поменял, не знаю - попробуйте поинтересоваться на форуме. Вы ведь посылаете mobi, правда?

**Comment by xatage** [comment]
Да, посылаю mobi. Пробовал в config поменять на azw3 (хотя на выходе всё-равно был .mobi файл - так и должно быть?), но тоже безрезультатно и Amazon их просто не принимает. Сначала думал, что дело в почте. Правда после того как вручную всевозможные варианты перепробовал (перенаправить письмо, которое предварительно через sendToKindle отправил себе на почту; отправить книгу без темы, с темой "Sent to Kindle") и все они без проблем появлялись в библиотеке Kindle, я уже решил, что тут дело должно быть именно в какой-то несовместимости. 

Попробую что-нибудь разузнать на форуме, спасибо за ссылку.
