### ISSUE TITLE
Проблема с типом документа в Kindle

### ISSUE THREAD

**Issue by DrDru2** [rupor-github/fb2mobi#45]
Здравствуйте,
столкнулся с такой проблемой. Конвертирую книгу в mobi, заливаю в читалку.
В списке эта книга отображается как doc, а не book.
Возможно ли добавить возможность менять/удалять Personal Doc Tag [PDOC]  при конвертации.
Спасибо.

**Comment by rupor-github** [comment]
Почитайте пожалуйста документацию на WiKi. Вот [здесь](kindleRemovePersonalLabel): описано применение тага **kindleRemovePersonalLabel** и вообще много всего полезного.
