### ISSUE TITLE
Error while converting file (MacOS 10.11.4 with python3.3 from ports)

### ISSUE THREAD

**Issue by DMinsky** [rupor-github/fb2mobi#9]
Every time when I'm trying to convert some fb2 book I get this error:

```
bash-3.2$: python3.3 fb2mobi.py /Users/user/Downloads/some_book.fb2 
INFO: Converting "some_book.fb2"...
INFO: Using profile "default".
INFO: Converting fb2 to html...
INFO: Applying XSLT transformations "/Users/user/Downloads/fb2mobi-master/spaces.xsl"
CRITICAL: Error while converting file "/Users/user/Downloads/some_book.fb2"
```

Where can I find more detailed log? (MacOS 10.11.4 with python3.3 from ports)
Also, when I'm using fb2conv-gui-1.8 tool from http://www.the-ebook.org/forum/viewtopic.php?t=28447&postdays=0&postorder=asc&start=0 on the same file - everything works as well.

**Comment by gmk57** [comment]
You can display debug log on the screen with `--console-level DEBUG` command-line parameter and/or write it to file with `--log somedir\somefile.log` parameter.

Does the problem occur with all books or one particular book? In the latter case, could you share it?

**Comment by rupor-github** [comment]
Judging by the command line you provided (you are not running packaged application - simply because I do not know how to produce packages app for the Mac) my guess would be that you do not have one or mode dependencies installed: cssutils, lxml, Pillow, PyHyphen. I amd sure in case of fb2conv-gui-1.8 it is packaged with dependencies.

**Comment by DMinsky** [comment]
Thanks @gmk57,

This problem occur with all books. If you want, I can send to you any of them. Also, here is a log with DEBUG level.

`bash-3.2$: python3.3 fb2mobi.py /Users/user/Downloads/some_book.fb2 --console-level DEBUG
INFO: Converting "some_book.fb2"...
INFO: Using profile "default".
INFO: Converting fb2 to html...
INFO: Applying XSLT transformations "/Users/user/Downloads/fb2mobi-master/spaces.xsl"
CRITICAL: Error while converting file "/Users/user/Downloads/some_book.fb2"
DEBUG: Getting details
Traceback (most recent call last):
  File "fb2mobi.py", line 222, in process_file
    fb2parser.generate()
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 223, in generate
    self.parse_description(child)
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 497, in parse_description
    self.parse_format(t, 'div')
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 782, in parse_format
    self.parse_p(e)
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 625, in parse_p
    self.parse_format(elem, ptag, pcss)
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 750, in parse_format
    hs = self.insert_hyphenation(elem.text)
  File "/Users/user/Downloads/fb2mobi-master/modules/fb2html.py", line 848, in insert_hyphenation
    return html.unescape(s) if not self.hyphenate or not self.hyphenator or self.header or self.subheader else self.hyphenator.hyphenate_text(html.unescape(s), self.replaceNBSP)
AttributeError: 'module' object has no attribute 'unescape'`

@rupor-github thanks. But I'm sure it's not because of dependencies. Just because I resolve all of them by using pip and installing all needed libraries before start converting.

**Comment by rupor-github** [comment]
This one is easy :) From https://docs.python.org/3/library/html.html: "html.unescape(s) New in version 3.4". You are using Python 3.3. Looks like 3.5 has been available on Mac: http://stackoverflow.com/questions/33535625/python-3-5-for-os-x-el-capitan

**Comment by DMinsky** [comment]
Oh, thanks! Now it's almost working ;)

```
INFO: Applying XSLT transformations "/Users/dmitry/Downloads/fb2mobi-master/spaces.xsl"
INFO: Processing took 9.63 sec.
INFO: Running kindlegen...
CRITICAL: kindlegen not found
```

I can't find kindlegen anywhere inside this repo.

**Comment by rupor-github** [comment]
I do not think we could distibute Amazon's programs that easily: https://www.amazon.com/gp/feature.html?docId=1000765211

**Comment by DMinsky** [comment]
Cool! Now it works like a charm ;) Thanks
